version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAScafoldingTestProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAScafoldingTestProject
  gitUsername: siqagituser
  gitBranch: main
